dvisionlab/Larvitar

README.md
imaging/loaders/nrrdLoader.js
package.json

fixed parsing for Int16

---

docs/image_io.js.html
docs/index.html
docs/loaders_nrrdLoader.js.html
docs/module-loaders_nrrdLoader.html
imaging/image_io.js
imaging/loaders/nrrdLoader.js
package.json

feat(gzip): added support for gzip nrrd images

---

imaging/tools/tools.io.js
imaging/tools/tools.main.js
imaging/tools/tools.state.js
index.js

Add methods to download cs tools state as json file and then upload it later.

Load & save cornerstone tools

---

imaging/image_tools.js
imaging/loaders/dicomLoader.js
imaging/tools/tools.default.js

feat(add eraser tool)

---

README.md
docs/image_rendering.js.html
docs/index.html
docs/module-imaging_rendering.html
imaging/image_rendering.js
package.json

- Fixed the problem detected when ww and/or wl are null
- Fixed US rendering (rgb colors)

fix(image_rendering): fixed rendering for US and XA images

---

imaging/image_rendering.js
imaging/tools/tools.main.js

Fix rendering passing imageIds from outside

Fix rendering

---

imaging/tools/tools.default.js
imaging/tools/tools.main.js

Prima era impossibile disattivare lo scroll

treat StackScrollMouseWheelTool as other tools

---

README.md
docs/index.html
package.json

Fix docs layout

---

docs/documentation/global.html
docs/documentation/image_parsing.js.html
docs/documentation/loaders_commonLoader.js.html
docs/documentation/loaders_multiframeLoader.js.html
docs/documentation/module-imaging_parsing.html
docs/examples/multiframe.html
imaging/image_parsing.js
imaging/loaders/commonLoader.js
imaging/loaders/multiframeLoader.js

- fix #82 
- fixed multiframe example with frame rate from tags
- added custom tags for multiframe in main object

fix: colored images

---

imaging/loaders/resliceLoader.js

It could appear a fast fix... but it took hours to find the problem 😂 
Fix #83

fix: colormaps for custom loaders

---

docs/examples/reslice.html
imaging/image_reslice.js
imaging/loaders/dicomLoader.js
imaging/loaders/resliceLoader.js
index.js

Using larvitar manager for reslice

fix: reslice memory

---

imaging/image_rendering.js

Fixed handlers using elementId from event variable

fix: handlers

---

docs/examples/base.html
docs/examples/reslice.html

fix: reslice example

---

imaging/loaders/multiframeLoader.js

fix: fixed spacing for multiFrame loader

---

README.md
imaging/image_parsing.js
imaging/image_rendering.js
imaging/image_utils.js
imaging/loaders/commonLoader.js
imaging/loaders/nrrdLoader.js
imaging/monitors/memory.js
index.js
package.json

- fixed memory leaks on render image
- added custom memory limit

fix: memory issues

---

README.md
docs/examples/defaultTools.html
docs/index.html
imaging/image_store.js
imaging/tools/tools.default.js
imaging/tools/tools.interaction.js
modules/vuex/larvitar.js
package.json
yarn.lock

Devono rimanere separati perchè i shift / ctrl agiscono su uno o sull'altro.

Fix: initialize also left button and store both buttons 

---

README.md
docs/examples/multiframe.html
imaging/image_rendering.js
imaging/loaders/multiframeLoader.js
package.json

- Added possibility to call updateImage with loadAndCacheImage
- Do not create a new canvas every time in multiframeloader

fix: multiframe memory leak

---

README.md
imaging/tools/tools.interaction.js
imaging/tools/tools.main.js
package.json

mouseButtonMask becomes an array when passing though "setToolActiveForElement".
Add a proper type check and handling.

fix mouse button mask check

---

README.md
imaging/image_anonymization.js
index.js
package.json
yarn.lock

Dicom anonymization and encryption

---

MIGRATION.md
README.md
imaging/tools/segmentation.js
imaging/tools/segmentations.md
index.js
package.json

BREAKING CHANGE: redefine getActiveLabelmapBuffer
feat: add loadMaskSlice
feat: add toggleVisibility
feat: set/get labelColor
feat: add config in initSegmentationModule

New seg api

---

README.md
imaging/imageLoading.js
package.json
yarn.lock

- cornerstone-core
- dicom parser
- cornestone-wado-image-loader
- cornestone-tools

feat: updated cornestone deps

---

README.md
imaging/tools/segmentation.js
imaging/tools/segmentations.md
imaging/tools/setLabelMap3D.js
package.json

override original code to use a non-blocking implementation

override setLabelMap3D

---

.github/workflows/build-docs.yml
.github/workflows/deploy.yml
README.md
docs/index.html
modules/vuex/larvitar.js
package.json

Added possibility to reset seriesIds in larvitar store vuex module.

feat: added resetSeriesIds

---

README.md
imaging/imageParsing.js
imaging/loaders/commonLoader.js
package.json

Fixed multiframe loader when using readFile instead of readFiles

fix: fixed multiframe for single image parsing

---

README.md
imaging/imageRendering.js
imaging/imageStore.js
modules/vuex/larvitar.js
package.json
yarn.lock

- added isColor, isMultiframe and isTimeserie (for 4d) in larvitar store viewport object
- Updated cornerstone-wado-image-loader and dicom-parser to last version

feat: added info in store, updated deps

---

README.md
docs/examples/multiframe.html
imaging/imageRendering.js
package.json

Fixed imageIndex to be consistent on all library, from 0 to n-1

fix: fixed image index from 0 to n-1

---

README.md
imaging/imageIo.js
package.json

fix: buildData sync

---

README.md
imaging/imageParsing.js
package.json

Fixed raise exception for memory allocation.

fix: memory exception

---

README.md
imaging/imageParsing.js
imaging/imageRendering.js
package.json
yarn.lock

- updated cornerstone-tools e wado-image-loader (minor fixes)
- updated larvitar build in examples folder
- fixed isTimeserie flag and index computation

fix: timeseries rendering

---

README.md

Saw 3 "cornestone" that are typos probably

cornestone -> cornerstone

---

README.md
docs/examples/defaultTools.html
imaging/imageTools.js
imaging/tools/interaction.js
index.js
package.json

- Activate key-related tools on all viewports 
- Store handlers in global variable, in order to: 
- remove them before adding again 
- implement a function to remove the listeners
- Update README with Develop section

fix mouse handlers add / remove

---

README.md
docs/documentation/imageStore.js.html
docs/documentation/index.html
docs/documentation/module-imaging_imageStore-Larvitar_Store.html
docs/documentation/module-imaging_imageStore.html
imaging/imageStore.js
package.json

fix: defineVue export

---

imaging/loaders/commonLoader.ts
package.json
yarn.lock

Risolve il problema del loading di multiframe usando la strategia di lettura del singolo file con update del manager.

fix: multiframe loading w/ updateLarvitarManager

---

README.md
docs/documentation/index.html
imaging/imageRendering.ts
imaging/imageStore.ts
package.json

Fixed an issue in which the viewport inverse attribute was every time set to true. In case of lut shape attribute shall be false, according to the original rendering.

fix: lut for Presentation LUT Shape Attribute INVERSE

---

README.md
docs/documentation/imageLoading.js.html
docs/documentation/index.html
docs/documentation/module-imaging_imageLoading.html
imaging/imageLoading.js
package.json

Ho portato la modifica nel branch master

fix: default order using instanceNumber (master-js)

---

README.md
docs/documentation/index.html
docs/examples/base.html
imaging/imageLoading.ts
imaging/imageTags.ts
package.json

- aggiunto default su instance number se esiste
- aggiunto controllo sul character set nel caso in cui la dicom tag sia malformata

fix: default order using instanceNumber

---

README.md
dist/imaging/imageRendering.d.ts
dist/imaging/imageStore.d.ts
dist/imaging/tools/segmentation.d.ts
docs/documentation/index.html
imaging/imageRendering.ts
imaging/imageStore.ts
package.json

@daron1337 credo manchi questo set perchè in pantera mi esce quella stringa di errore quando richiedo una fetta non ancora scaricata

fix: set pendingSliceId in 'updateImage' function

---

README.md
dist/imaging/loaders/commonLoader.d.ts
dist/imaging/loaders/multiframeLoader.d.ts
docs/documentation/index.html
docs/documentation/module-imaging_parsers_ecg.html
docs/documentation/module-imaging_tools_default.html
docs/documentation/module-imaging_tools_interaction.html
docs/documentation/module-imaging_tools_io.html
docs/documentation/module-imaging_tools_main.html
docs/documentation/module-imaging_tools_segmentation.html
docs/documentation/module-loaders_commonLoader.html
docs/documentation/module-loaders_multiframeLoader.html
docs/documentation/module-loaders_nrrdLoader.html
docs/documentation/module-loaders_resliceLoader.html
docs/documentation/module-monitors_memory.html
docs/documentation/module-monitors_performance.html
docs/documentation/module-waveforms_ecg.html
imaging/loaders/commonLoader.ts
imaging/loaders/multiframeLoader.ts
package.json

Fixed seriesId tag in multiframe manager

fix: seriesId in multiframe

---

docs/examples/WSToggle.html
imaging/tools/custom/WSToggleTool.js

Aggiunto loader in movimento in UI per verificare la responsività della UI. 
Trasformato il ciclo for in una funzione ricorsiva che viene richiamata con settimeout 0 ad ogni pixel. 
In questo modo è responsive ma molto lento, bisognerebbe provare a fare la stessa cosa ma con una riga intera / pacchetto di righe.

keep UI responsive

---

README.md
docs/documentation/index.html
docs/documentation/module-imaging_tools_interaction.html
docs/documentation/module-imaging_tools_io.html
docs/documentation/module-imaging_tools_main.html
docs/documentation/module-imaging_tools_segmentation.html
docs/documentation/module-waveforms_ecg.html
docs/examples/defaultTools.html
imaging/tools/default.ts
package.json

Avevamo erroneamente tolto dai default lo StackScroll tool, ho anche sistemato l'esempio.

Fix stacktool

---

README.md
docs/documentation/index.html
imaging/imageParsing.ts
imaging/imageUtils.ts
imaging/loaders/multiframeLoader.ts
imaging/loaders/nrrdLoader.ts
imaging/loaders/resliceLoader.ts
imaging/tools/custom/EllipticalRoiUSTool.ts
imaging/tools/custom/FreehandRoiUSTool.js
imaging/tools/custom/LengthUSTool.ts
imaging/tools/custom/RectangleRoiUSTool.ts
package.json

TODO: check why build is so slow

FIXED PixelSPacing for US case

---

README.md
dist/imaging/tools/custom/OverlayTool.d.ts
dist/imaging/tools/main.d.ts
docs/documentation/index.html
docs/examples/base.html
docs/examples/defaultTools.html
docs/examples/index.html
docs/examples/segmentationTools.html
docs/index.html
imaging/tools/custom/OverlayTool.js
imaging/tools/custom/OverlayTool.ts
imaging/tools/default.ts
imaging/tools/main.ts
imaging/tools/types.d.ts
imaging/types.d.ts
package.json

TSK. 662 pantera 
-use 838.dcm in base example to test

implemented overlay tool

---

README.md
docs/documentation/index.html
imaging/imageParsing.ts
imaging/imageRendering.ts
imaging/loaders/multiframeLoader.ts
imaging/tools/custom/EllipticalRoiUSTool.ts
imaging/tools/custom/LengthUSTool.ts
imaging/tools/custom/RectangleRoiUSTool.ts
package.json

flag->this.options.deleteIfHandleOutsideImage = false;

implemented possibility to drag measurements outside of image boundaries

---

README.md
dist/imaging/tools/custom/WwwcRemoveRegionTool.d.ts
docs/documentation/index.html
docs/examples/base.html
docs/examples/defaultTools.html
imaging/tools/custom/WwwcRemoveRegionTool.js
imaging/tools/default.ts
package.json

Minor fixes on remove ww/wc region tool. Better handling remove. Region rectangle now Black with green border

Fix remove wwwcregion

---

README.md
docs/documentation/index.html
imaging/loaders/multiframeLoader.ts
package.json

clearImageCache non riusciva a pulire i frame da cornerstone perche non se li ritrovava mappati nell'imageStore.
Prima:
https://github.com/dvisionlab/Larvitar/assets/80772252/ccf43681-4288-426b-b179-d528658d46d9
Dopo:
https://github.com/dvisionlab/Larvitar/assets/80772252/54081cdc-4022-4109-b292-05d60a7eb76c

fix: added multiframe info to imageStore

---

README.md
dist/imaging/imageStore.d.ts
docs/documentation/index.html
imaging/imageParsing.ts
imaging/imageRendering.ts
imaging/imageStore.ts
imaging/loaders/dicomLoader.ts
package.json

Aggiunta una variabile con la lista di tutte le imageId, vanno a True

feat: add cache status for loadAndCache

---

README.md
docs/documentation/index.html
imaging/imageTags.ts
package.json

"Data nascita sbagliata nei metadati (e fix formato)": [TD-1184](https://dicomvision.atlassian.net/browse/TD-1184)
@laura-borghesi-lum00n fammi sapere se riesci ancora ad ottenere la data sballata di 1 giorno
[TD-1184]: https://dicomvision.atlassian.net/browse/TD-1184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: datetime repr

---

README.md
dist/imaging/tools/custom/LengthPlotTool.d.ts
docs/documentation/index.html
imaging/tools/custom/LengthPlotTool.ts
package.json

Ora il plot si aggancia al canvas specifico in modo da funzionare con layout multipli

feat: multicanvas plot

---

README.md
dist/imaging/tools/custom/LengthPlotTool.d.ts
docs/documentation/index.html
docs/examples/defaultTools.html
imaging/tools/custom/LengthPlotTool.ts
package.json

Ora il plot si adatta alla dimensione del div contenitore. Utile al resize della finestra o soprattutto al resize dei layout multipli

feat: plot resizes on parent div resize

---

README.md
dist/imaging/tools/custom/LengthPlotTool.d.ts
docs/documentation/index.html
imaging/tools/custom/LengthPlotTool.ts
package.json

Ora il plot si adatta in base alla misura presa su una specifica slice. Se quella slice non ha la misurazione il plot sparisce.
Come side effect il plot si aggiorna in real time mentre si traccia, forse più carino.
Ora se si riapre una serie cachate anche il plot viene renderizzato.

feat: plot by slice

---

README.md
docs/documentation/index.html
imaging/tools/custom/WwwcRemoveRegionTool.js
package.json

Togliendo quel branch si evita il loop di rendering infinito nel momento in cui si cancella l'ultimo "quadrato" bloccando il funzionamento del wwwc. 
Remove region anche cosi sembra funzionare correttamente.

fix: remove region tool

---

README.md
docs/documentation/index.html
imaging/tools/custom/WwwcRemoveRegionTool.js
package.json

Remove region calc applied on render, this enables:
- Remove region loaded from db
- Remove region of cached series
- live calc during drawing

feat: apply remove region from db data

---

README.md
dist/imaging/tools/custom/thresholdsBrushTool.d.ts
docs/documentation/index.html
imaging/tools/custom/thresholdsBrushTool.js
package.json

Add a dynamic calculation of threshold for threshold brush

Update thershold brush

---

README.md
dist/imaging/tools/custom/LengthPlotTool.d.ts
docs/documentation/index.html
imaging/tools/custom/LengthPlotTool.ts
package.json

Ora il plot si completa con 3 click. L'offset non si setta più con la rotella ma con il movimento del mouse dopo il secondo click.
Da provare per capire se l'interazione è accettabile/da migliorare

feat: 3 click plot draw

---

README.md
docs/documentation/index.html
imaging/loaders/multiframeLoader.ts
imaging/tools/custom/OverlayTool.ts
package.json

Risolto il problema del "lag" con immagini multiframe JPEG Lossy.
La conversione dell'array era troppo lenta, risolto ritornando la vista nativa del typed array.
Aggiunto un check per overlayTool (si rompeva con DSA)

fix: getPixelData

---

README.md
dist/imaging/tools/segmentation.d.ts
docs/documentation/index.html
docs/examples/ecg.html
imaging/waveforms/ecg.ts
package.json

Use Plotly.animate instead of Plotly.extendTraces to enhance performance. 
!! Plotly.animate does not work with webgl scatter trace type

Fix ECG rendering performance

---

dist/imaging/tools/custom/gridTool.d.ts
dist/imaging/tools/custom/gridToolUtils.d.ts
dist/imaging/tools/custom/utils/gridToolUtils/gridToolUtils.d.ts
imaging/tools/custom/gridTool.ts
imaging/tools/custom/gridToolUtils.ts
imaging/tools/custom/utils/gridToolUtils/gridToolUtils.ts
imaging/tools/default.ts
imaging/tools/types.d.ts
yarn.lock

grid tool fully implemented with: 
- customizable grid center with user click
- customizable grid pattern squares dimension in configuration of the class
- grid's pixel data available in class configuration

Ts kgrid tool

---

README.md
dist/imaging/imageUtils.d.ts
docs/documentation/index.html
docs/examples/base.html
docs/examples/metadataTable.html
imaging/imageUtils.ts
package.json

- sistemato il parsing delle tag nestate (sequence)
- aggiunto bottone (in base example) il quale apre una tab con tabella metadati, anche con ricerca
- aggiunta la possibilità di fare drag and drop e caricare dicom (in base example)
- aggiunti bottoni (in base example) per navigare tra le serie (o anche le frecce dx sx)

feat: drag&drop and metadata table

---

docs/.vuepress/config.js
package.json
yarn.lock

https://ecosystem.vuejs.press/plugins/search/slimsearch.html

feat: added search plugin

---

docs/.vuepress/config.js
docs/api/interacting.md
docs/api/modules/tools/default.md
docs/api/modules/tools/dvTools.md
docs/api/modules/tools/initialization.md
docs/api/modules/tools/segmentation.md
docs/api/modules/tools/tools.md
imaging/tools/main.ts
imaging/tools/segmentation.ts
package.json

**Added Documentation for Interaction Tools and Tool Management**
In this pull request, I've added documentation related to interaction tools and their management within the project.
- **Interaction Tools**
This md serves as an introduction to the various interaction tools available in the application. 
- **Initialize and Manage Tools**
Provides detailed instructions on how to initialize and configure tool. 
- **Default and Custom Tools**
Explains the use of both default and custom tools within the application.
- **Segmentation Tools**
Focuses on tools used for image segmentation
- **DvTools**
A specialized document for D/Vision Lab's suite of custom tools, highlighting their advanced capabilities in annotation, segmentation, measurement, and visualization (and references).

Tools docs

---

imaging/imageTags.ts
package.json

- Added function for multiple values parsing 
```
function processMultiValues(
dataSet: DataSet,
propertyName: string,
count: number,
method:
| "uint16"
| "uint32"
| "string"
| "float"
| "int16"
| "int32" = "uint16"
) 
```
- Add aquisition matrix management 00181310

Fix tag parsing 

---

imaging/imageTags.ts
package.json

https://dicom.innolitics.com/ciods/mr-image/mr-image/00181310 - molteplicity 4 instead of 3

image tag molteplicity fix

---

imaging/tools/default.ts
imaging/tools/types.ts
imaging3d/tools/main.ts
imaging3d/types.ts
package.json

- fix cursor setting 
- fix initialization cs3dTools style type
- expose cs3d types

Fixes: types - cursors

---

docs/api/modules/loaders/singleFrameLoader.md
docs/examples/singleFrame.html
imaging/MetaDataTypes.ts
imaging/loaders/commonLoader.ts
imaging/loaders/multiframeLoader.ts
imaging/loaders/nrrdLoader.ts
imaging/loaders/resliceLoader.ts
imaging/loaders/singleFrameLoader.ts
imaging/types.ts
package.json

As for multiFrame custom loader, we are using wadoImagLoader internal decoding functions in order to support all transfer syntaxes for single frame buffer.

Single Frame Decoders

---

docs/examples/cs3D/baseMpr.html
imaging/imageLoading.ts
imaging/imageStore.ts
imaging/imageUtils.ts
imaging/loaders/singleFrameLoader.ts
imaging/types.ts
imaging3d/imageLoading.ts
imaging3d/imageParsing.ts
imaging3d/imageRendering.ts
imaging3d/metadataProviders/metadataProviders.ts
imaging3d/types.ts
package.json

Prima di mergiare fate qualche prova. Ho sistemato la gestione dei metadati e questo è abbastanza trasparente, ho poi aggiunto la camera e tutta la volume viewport di cs3D con i suoi metodi nell oggetto viewport dello store di larvitar

Store fixes
