- docs/examples/base.html
- imaging/image_rendering.js
- imaging/image_store.js
- imaging/image_utils.js
- imaging/loaders/commonLoader.js
- imaging/loaders/dicomLoader.js
- imaging/loaders/nrrdLoader.js
- index.js
- modules/vuex/larvitar.js
- to populate the manager simply use sync and real time function populateLarvitarManager
- to cache images and update manager with cached pixeldata use cacheImages
- cacheimages returns progress in callback and save progress into store.state.series[seriesId]["progress"]
TODO:
- Fix VueX store (addSeriesIds) and setProgress function
See base.html for a live example
> Cache fixes

- imaging/image_io.js
- index.js
Implemented async version of buildData: it does not block the js interpreter (UI spinner continue running etc...)
Use this in dicom.vision and doors
> build data async

- imaging/image_store.js
fix #111 
In any case, you need to set the active tool in larvitar store using:
`larvitar_store.set("leftMouseHandler", <TOOLNAME>);`
or for vuex
`store.dispatch("larvitar/setLeftMouseHandler",  <TOOLNAME>);`
> fix: set in store

- README.md
- docs/examples/base.html
- docs/examples/colorMaps.html
- docs/examples/defaultTools.html
- docs/examples/layers.html
- docs/examples/multiframe.html
- docs/examples/reslice.html
- imaging/image_io.js
- imaging/image_loading.js
- imaging/image_parsing.js
- imaging/loaders/commonLoader.js
- imaging/loaders/multiframeLoader.js
- imaging/monitors/memory.js
- index.js
- package.json
I've added some functionalities to monitor memory usage with [performance.memory ](https://developer.mozilla.org/en-US/docs/Web/API/Performance/memory).
Unfortunately it currently support only Chrome, Edge and Opera.
Here's how to use it:
- `populateLarvitarManager` returns the `manager `or `throw` an **error** (`throw new Error( "Larvitar Manager has not been populated: not enough memory");`) if **memory is not enough**
- `readFiles `returns a `callback `with the **parsed stack** and **error message**. If there's an _error_ (eg not enough memory), the **parsed stack** is `null`
- `buildData `and `buildDataAsync `return the **typed array** or `throw `an **error** (`throw new Error("Data has not been builded: not enough memory");`)  if there's **not enough memory** to build the _contiguous …
> Issue#129 memory

- README.md
- imaging/image_parsing.js
- package.json
Reset typed array and file object inside allSeriesStack object before setting it to null on memory errors.
This strategy allows gc to correctly deallocate arrays.
> fix: reset memory after parsing

- README.md
- docs/index.html
- imaging/image_io.js
- imaging/image_rendering.js
- package.json
- clean single wado image loader uri instead of call purgecache (wrong)
- set seriesIds in store for decaching purpose
- commented useless lines in buildHeader
Always call `larvitar.cleanImageCache(seriesId)` when a canvas is destroyed , wado imageloader has its internal dataSetCache
> fix: wadoimageloader clean cache

- README.md
- docs/examples/base.html
- docs/examples/defaultTools.html
- docs/index.html
- imaging/image_layers.js
- imaging/image_rendering.js
- imaging/image_store.js
- imaging/image_tools.js
- imaging/image_utils.js
- imaging/tools/tools.interaction.js
- imaging/tools/tools.main.js
- index.js
- package.json
⚠️ ⚠️ ⚠️ BREAKING CHANGE : **setToolActive** has a new signature: setToolActive(toolName, options, viewports, doNotSetInStore). The latter param is optional. 
**Note:** IMHO I think we should update all 3 params (scale, translation, voi) at each mouse interaction. This would mean delete all the get / set listeners for handles each time a new tool is activated (press left / right button and shift / ctrl keys). A lot less code, since we would not need to know which tool is active. Moreover, it will fit also the "touch" interactions, otherwise we will have to set another "touchActiveTool".
> Mouse handlers reworking

- README.md
- imaging/loaders/nrrdLoader.js
- package.json
My guess was right, it was a problem of the nrrd loader.
Since we always tested nrrd images with same number of rows & columns, this bug was never highlighted.
The problem was simple, rows index and columns index were inverted.
It's fixed in v0.17.1 which is not yet on npm.
fix #156
> fix: fixed nrrd rendering, wrong row/col index

- README.md
- imaging/tools/segmentation.js
- imaging/tools/segmentations.md
- package.json
User has now two ways to enable brush tools: 
- directly the `setToolActive` / `setToolDisabled` api, in this case he has to handle brush type (thresholds or not), props (radius etc) and tool switching
- Otherwise, Larvitar implements the utility functions `enableBrushTool` and `disableBrushTool` that internally handle brush type and props with a single call.
> feat: utils brush api

- README.md
- docs/documentation/imageLoading.js.html
- docs/documentation/index.html
- docs/documentation/module-imaging_imageLoading.html
- imaging/imageLoading.js
- package.json
- yarn.lock
- updated wado image loader
- removed refs for workers from imageloading
see https://github.com/cornerstonejs/cornerstoneWADOImageLoader/releases/tag/v4.10.2
> fix: wado image loader for offline workers

- README.md
- docs/documentation/imageStore.js.html
- docs/documentation/index.html
- docs/documentation/module-imaging_imageStore.html
- imaging/imageStore.js
- modules/vuex/larvitar.js
removed the Vue dependency.
In order to use the larvitar store from a Vue.js application user needs to call larvitar store passing also Vue instance as additional parameter
`initLarvitarStore(store, "larvitar", true, Vue);`
where store is the Vuex Store and Vue is the Vue instance (`import Vue from "vue";`)
> fix: Vue dependency

- README.md
- docs/documentation/index.html
- imaging/imageIo.ts
- package.json
In realtà sono le serie ad essere invertite e non le maschere.
Il problema è stato causato dal vecchio fix per mostrare la serie dritta in caso di MPR o VR:
riassegnando le immagini riordinate a `series.imageIds` quest'ultimo se le portava dietro mostrando la serie invertita anche nelle altre modalità, era necessario ordinarle solo localmente al metodo.
[TD-1092](https://dicomvision.atlassian.net/browse/TD-1092)
[TD-1092]: https://dicomvision.atlassian.net/browse/TD-1092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: inverted series after advanced view

- CHANGELOG.md
- docs/api/rendering.md
- docs/examples/4d.html
- docs/examples/base.html
- docs/examples/dsa.html
- docs/examples/ecg.html
- docs/examples/multiframe.html
- docs/examples/singleFrame.html
- imaging/imageRendering.ts
- imaging/loaders/dsaImageLoader.ts
- imaging/postProcessing/applyDSA.ts
- imaging/tools/custom/gspsUtils/maskUtils.ts
- imaging/tools/interaction.ts
- imaging/tools/main.ts
- imaging/types.d.ts
- imaging/waveforms/ecg.ts
- index.ts
- package.json
**Modifiche principali:**
- Deprecazione di updateImage: Il metodo updateImage è stato contrassegnato come deprecato e non dovrebbe più essere utilizzato nelle implementazioni future.​
- Utilizzo di renderImage: Tutte le funzionalità precedentemente gestite da updateImage sono ora centralizzate in renderImage, che diventa l'unico metodo per il rendering delle immagini.​
**Implicazioni per gli sviluppatori:**
- Aggiornamento del codice: È consigliato sostituire tutte le chiamate a updateImage con renderImage per garantire la compatibilità con le versioni future della libreria.​
- Uniformità dell'API: Questa modifica favorisce una maggiore coerenza nell'utilizzo dell'API, riducendo la curva di apprendimento e semplificando la manutenzione del codice.​
In conclusione, questa Pull Request …
> feat: updateImage deprecation

- docs/examples/gsps.html
- imaging/tools/custom/gspsTool.ts
- imaging/tools/custom/gspsUtils/annotationAndOverlayRetrievalUtils.ts
**Improved Image Loading Performance**
- The `activeElement.image` polling process has been optimized to avoid blocking execution: Instead of using setInterval, we now wait asynchronously for the image to be available (using `cornerstoneimagerendered `event), significantly reducing load time.
**Fixed Missing Icon for Active WWWC Tool**
- The UI now correctly displays the tool icon when the Window Width/Level (WWWC) tool is active.
**Preserved Contrast Values When Toggling GSPS**
- Previously, toggling GSPS off would reset contrast values. Now, user-selected contrast and zoom values are maintained and only gsps values are reset.
**Removed Unnecessary Warning: "Shutter overlay group is undefined."**
> fix GSPS tool 

- docs/examples/defaultTools.html
- docs/examples/gsps.html
- docs/examples/watershedSegmentationTool.html
- imaging/tools/custom/LengthPlotTool.ts
- imaging/tools/custom/gspsTool.ts
- imaging/tools/custom/gspsUtils/annotationAndOverlayRetrievalUtils.ts
- package.json
- Fixed the LengthPlotTool example to properly update the offset using the mouse wheel while holding Shift.
- Enhanced the defaultTools example by adding a plot and info description for better clarity.
- Resolved issues in the Watershed example by ensuring correct rendering and adding masks to the viewport.
> Fix examples

- imaging/tools/custom/gspsTool.ts
**case**: tool disabled without previously being enabled
> fix gsps and original viewport undefined

- CHANGELOG.md
- docs/api/rendering.md
- docs/examples/4d.html
- docs/examples/base.html
- docs/examples/dsa.html
- docs/examples/ecg.html
- docs/examples/multiframe.html
- docs/examples/singleFrame.html
- imaging/imageRendering.ts
- imaging/imageTools.js
- imaging/postProcessing/applyDSA.ts
- imaging/tools/custom/gspsUtils/maskUtils.ts
- imaging/tools/main.ts
- imaging/types.d.ts
- imaging/waveforms/ecg.ts
- package.json
This PR introduces the `renderOptions` parameter in the `renderImage` function, replacing the previous `defaultProps` 
The new `RenderProps` type provides a more structured and flexible way to configure rendering settings, including:
- Caching behavior (cached)
- Image index (imageIndex)
- Viewport transformations: scale, rotation, translation
- Windowing and contrast settings (voi)
- Colormap selection (colormap)
- Default values for transformations and contrast adjustments
**Breaking Changes**
- The `defaultProps` parameter has been replaced by `renderOptions`.
- Existing calls to renderImage should be updated to pass a `RenderProps` object.
> feat: new rendering options

- imaging/loaders/multiframeLoader.ts
- package.json
This PR fixes an issue with mutliframe color images with no standard JPEG8BIT encoding.
Since` context.createImageData` creates always a RGBA array, we need to use the `rgba` boolean flag in the `convertColorSpace `function set to True.
Moreover, the colorBuffer to be passed to convertColorSpace is `imageData.data`
See: https://developer.mozilla.org/en-US/docs/Web/API/ImageData/data
> fix: convertColorSpace for multiframe RGBA images lossy jpeg

- imaging/loaders/dsaImageLoader.ts
- package.json
This PR ensures that the window width (windowWidth) and window center (windowCenter) of images created with DSA-applied masks are correctly initialized by default to match those of the original image (srcImage).
**Key Changes & Behavior:**
- Default Values from Original Image:
If the original image (srcImage) has defined windowCenter and windowWidth, those values are used for the newly created image.
- Fallback Mechanism:
If windowCenter (middle of the computed range) or windowWidth (based on the pixel intensity range) are missing in the original image, fallback values are computed based on pixel intensity:
```
const computedWindowWidth = (maxPixelValue - minPixelValue) / 2;
const computedWindowCenter = (maxPixelValue + minPixelValue) / 2;
```
> FIX dsa: wwwl from srcImage

- imaging/imageParsing.ts
- package.json
**Purpose of the PR**
This PR:
- Fixes incorrect handling of DICOM values with multiplicity > 1 (i.e., arrays with multiple items).
- Refactors parseSequence to correctly parse sequence elements, which may also contain arrays and nested sequences.
**Main Fixes in convertQidoMetadata**
-  `value = item[key]?.Value ? item[key].Value[0] : undefined; `  would return a single value if the length was 1 — `data[key].Value.length > 1 ? data[key].Value : data[key].Value[0]` this strips away the array structure even when the value should be treated as a list
> Fix: convert qido metadata

- imaging/imageRendering.ts
- index.ts
- package.json
This PR refactors the image cache clearing logic to improve modularity, readability, and maintainability and implements DSA image cache clearing. The changes include:
- Separated image cache logic into two dedicated functions:
`clearStandardImageCache(uniqueUID: string)`
`clearDSAImageCache(uniqueUID: string)`
- Extracted shared logic into a reusable helper:
`clearSingleImageCache(imageId: string)`
> Refactor image cache clearing: Separate DSA and regular image cache logic

- docs/examples/base.html
- imaging/imageManagers.ts
- package.json
Fix `removeDataFromImageManager` function: in case of multiframe series, check `dataSet` existance before resetting `dataSet.byteArray` value.
> fix: reset dataSet byteArray for multiframe series

- imaging/imageParsing.ts
- package.json
This PR restructures nested values so that their keys (tags) conform to the Larvitar standard format, using the pattern:
`const newKey = 'x${key.toLowerCase()}';`
This ensures consistent key naming throughout the data structure.
> fix sequence key/tags to match larvitar  standards

- docs/examples/cs3D/base.html
- docs/examples/cs3D/baseMpr.html
- docs/examples/cs3D/multiframe.html
- imaging/tools/default.ts
- imaging3d/tools/custom/exampleCustomTool.ts
- imaging3d/tools/main.ts
- package.json
**Custom Tool Differentiation by Mode:**
Refactored customTool and allToolsList resolution using structured logic.
Explicitly separate tool resolution and activation logic for:
- 2D (e.g., cornerstone - dvTools)
- 3D (e.g., cornerstone3D -dvTools3D)
- MPR (multi-planar reconstruction - dvToolsMPR)
Prevents attempting to register or activate a 2D tool on a 3D canvas or tool group, avoiding runtime issues.
**Correct MPR Tool Activation in example:**
- Ensures MPR tools are only activated on the three orthogonal MPR canvases (axial, sagittal, coronal).
- Ensures 3D tools (e.g., volume navigation, slab rendering) are only applied to the acquisition (3D) canvas.
> Fix add tool and cs3D examples

- docs/api/rendering.md
- imaging/imageRendering.ts
- imaging/tools/custom/gspsTool.ts
- imaging/tools/types.ts
- imaging/types.ts
- package.json
**Description:**
This PR introduces a new resizeViewport utility function that resizes a Cornerstone viewport depending on whether the displayed image is anisotropic (i.e., differing row and column pixel spacing). The change ensures correct rendering behavior by adjusting the displayedArea when needed.
**Key Changes:**
- `resizeViewport`:
Accepts either a DOM element or string ID.
Determines if the target image is anisotropic using isAnisotropic.
If anisotropic:
Fetches the current viewport.
Updates displayedArea to normalize spacing via resizeAnisotropicViewport.
If not:
Uses standard cornerstone.resize() with fitToWindow enabled.
- `isAnisotropic`:
Checks if the row and column pixel spacing differ for a given element ID using the global store.
- `resizeAnisotropicViewport`:
Constructs a …
> fix anisotropic images rendering

- docs/api/modules/loaders/singleFrameLoader.md
- docs/examples/singleFrame.html
- imaging/imageManagers.ts
- imaging/loaders/singleFrameLoader.ts
- index.ts
- package.json
This pull request introduces improvements to single-frame DICOM image cache management and updates the example code to better demonstrate multi-frame handling. The main changes include the addition of a method to access the single-frame cache, enhanced cache clearing logic and documentation updates.
**Single-frame cache management:**
* Added a new `getSingleFrameCache` function to allow retrieval of cached single-frame data by image ID or for all images, and exported it in `index.ts` for external use. 
* Improved `clearSingleFrameCache` to ensure cache entries are properly deleted when clearing by image ID or clearing all entries.
* Updated cache clearing logic in `resetImageManager` and `removeDataFromImageManager` to invoke `clearSingleFrameCache` for each relevant image, ensuring …
> fix: single frame cache cleaning with image managers

- imaging/imageParsing.ts
- package.json
**Fix RGB single-frame image visualization**
Correctly decode palette color LUT data (x00281201, x00281202, x00281203 - bluePaletteColorLookupTableData, redPaletteColorLookupTableData,greenPaletteColorLookupTableData) in `convertQidoMetadata  `using `inlineBinaryToUint16Array `(since their VR is OW and values are 16-bit).
> fix: rgb singleframe parsing
